#
# Check https://circleci.com/docs/2.0/ for more details
#
version: 2.1

executors:
  jvm:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

  nodejs:
    docker:
      - image: circleci/node:lts

  native:
    docker:
      - image: cimg/base:2020.01

jobs:

  build:
    executor:
      name: jvm

    steps:
      - checkout

      - run:
          name: Collect files for dependencies cache key
          command: |
            find . -path ./examples -prune -o -name '*.gradle*' -type f -print0 \
            | sort -z \
            | xargs -0 cat \
            > /tmp/circleci_cache_key

      - restore_cache:
          name: Restore dependencies cache
          keys:
            - v2-dependencies-{{ checksum "/tmp/circleci_cache_key" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: ./gradlew build

      - restore_cache:
          name: Restore protobuf cache
          keys:
            - v3-protobuf-3.10.1

      - run:
          name: Build protoc and protobuf conformance-test-runner
          command: |
            cd ~
            if [ -e ./protobuf/install/bin/protoc -a -e ./protobuf/conformance/conformance-test-runner ]; then
              exit
            fi
            curl -sSLO https://github.com/protocolbuffers/protobuf/releases/download/v3.10.1/protobuf-all-3.10.1.tar.gz
            tar xzvf protobuf-all-3.10.1.tar.gz
            mv protobuf-3.10.1 protobuf
            cd protobuf
            ./configure --prefix="$(pwd)/install"
            make
            make install
            cd conformance
            make

      - save_cache:
          name: Save protobuf cache
          paths:
            - ~/protobuf
          key: v3-protobuf-3.10.1

      - run:
          name: Ensure bundled types are up-to-date
          command: |
            export PATH="$PATH:$HOME/protobuf/install/bin"
            # need to stop the gradle daemon from the earlier step so it can pick up the new PATH value
            ./gradlew --stop
            ./gradlew -Dprotoc.path=$HOME/protobuf/install \
              :runtime:generateWellKnownTypes \
              :runtime:generateTestTypes \
              :protoc-gen-kotlin:lib:generateProto \
              :conformance:lib:generateProto
            if [ -n "$(git status --porcelain)" ]; then
              echo "*** Found uncommitted changes to bundled types: ***"
              git status
              exit 1
            else
              exit 0
            fi

      - run:
          name: Publish artifacts to local maven repository
          command: |
            ./gradlew publishToMavenLocal
            echo "Published files:"
            find $HOME/.m2/repository -type f

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .m2/repository

      - run:
          name: Build conformance test suite
          command: ./gradlew :conformance:lib:assemble :conformance:jvm:installDist :conformance:native:build

      # persist files necessary to run conformance tests
      - persist_to_workspace:
          root: .
          paths:
            - conformance/test-conformance.sh
            # jvm
            - conformance/jvm/build/install/conformance
            - conformance/jvm/failing_tests.txt
            # js
            - build/js
            - conformance/js/failing_tests.txt
            - conformance/js/run.sh
            # native
            - conformance/native/build/bin/linux/debugExecutable/conformance.kexe
            - conformance/native/failing_tests.txt

      - save_cache:
          name: Save dependencies cache
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "/tmp/circleci_cache_key" }}
          when: always


  conformance_jvm:
    executor:
      name: jvm

    steps:
      - attach_workspace:
          at: ~/project

      - restore_cache:
          name: Restore protobuf cache
          keys:
            - v3-protobuf-3.10.1

      - run:
          name: Run JVM conformance tests
          command: |
            export CONF_TEST_PATH=~/protobuf/conformance/conformance-test-runner
            ./conformance/test-conformance.sh jvm


  conformance_js:
    executor:
      name: nodejs

    steps:
      - attach_workspace:
          at: ~/project

      - restore_cache:
          name: Restore protobuf cache
          keys:
            - v3-protobuf-3.10.1

      - run:
          name: Run JS conformance tests
          command: |
            export CONF_TEST_PATH=~/protobuf/conformance/conformance-test-runner
            ./conformance/test-conformance.sh js


  build_examples:
    executor:
      name: jvm

    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - run:
          name: Setup local maven repository
          command: mv .m2 $HOME/

      - run:
          name: Collect files for dependencies cache key
          command: |
            find ./examples -name '*.gradle*' -type f -print0 \
            | sort -z \
            | xargs -0 cat \
            > /tmp/circleci_cache_key

      - restore_cache:
          name: Restore dependencies cache
          keys:
            - v1-examples-dependencies-{{ checksum "/tmp/circleci_cache_key" }}
            # fallback to using the latest cache if no exact match is found
            - v1-examples-dependencies-

      - run:
          name: Build all examples
          command: |
            for d in examples/*; do
              set -e
              [ -d "$d" ] || continue
              echo "== $d =="
              pushd "$d" >/dev/null
              ../../gradlew build
              popd >/dev/null
            done

      - save_cache:
          name: Save dependencies cache
          paths:
            - ~/.gradle
          key: v1-examples-dependencies-{{ checksum "/tmp/circleci_cache_key" }}
          when: always

conformance_native:
    executor:
      name: native

    steps:
      - attach_workspace:
          at: ~/project

      - restore_cache:
          name: Restore protobuf cache
          keys:
            - v3-protobuf-3.10.1

      - run:
          name: Run Native conformance tests
          command: |
            export CONF_TEST_PATH=~/protobuf/conformance/conformance-test-runner
            ./conformance/test-conformance.sh linux

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - conformance_jvm:
          requires:
            - build
      - conformance_js:
          requires:
            - build
- conformance_native:
          requires:
            - build
      - build_examples:
          requires:
            - build
